### ISSUE TITLE
/play is broken for some songs

### ISSUE THREAD

**Issue by TheAlienDoctor** [UFO-Studios/AlienBot-Discord#20]
When using the /play command, the bot will join the server, update the /play message to the song name embed then leave the vc.

**Comment by MDxWARRIORxOP** [comment]
oh, intresting. could be why alienbot has been restarting a lot lately

**Comment by MDxWARRIORxOP** [comment]
exactly

**Comment by MDxWARRIORxOP** [comment]
so it turns out it dosent work with our test bot aswell
