### ISSUE TITLE
NameMC command is broken

### ISSUE THREAD

**Issue by TheAlienDoctor** [UFO-Studios/AlienBot-Discord#21]
No matter what username is used, the NameMC command will always show this error. Even if a Java player exists with that name.

![Screenshot 2022-09-28 174239](https://user-images.githubusercontent.com/60036656/192840053-e1a7c7ca-982d-4846-8e05-e212a4ecd8c5.png)

**Comment by MDxWARRIORxOP** [comment]
oh, ill look into it, thanks for reporting!

**Comment by NiceygyLive** [comment]
Thats not an us problem, mojang have stopped some parts of the api. Ill have a proper look into it asap

**Comment by TheAlienDoctor** [comment]
Anything that doesn't work on our bot is an us problem. If features aren't going to be working due to stuff out of our control then they need to be removed.

**Comment by NiceygyLive** [comment]
Well it's still in the dark how much will be removed, so I'm archiving it for the time being

**Comment by TheAlienDoctor** [comment]
The command should be temporarily removed until it is able to function again then. It doesn't look great to have broken commands

**Comment by NiceygyLive** [comment]
Already done!

**Comment by TheAlienDoctor** [comment]
Thankyou!

**Comment by MDxWARRIORxOP** [comment]
Instead of removing the command, i will just remove the username history feature, which is causing the issue

**Comment by MDxWARRIORxOP** [comment]
Fixed by removing the username history feature, which is now removed from mc api :D
