### ISSUE TITLE
Update all to mongo

### ISSUE THREAD

**Issue by NiceygyLive** [UFO-Studios/AlienBot-Discord#24]
We need to move over all the db bits currently using firebase to mongo. This is the todo for it!

##ToDo
 Make a function for mongo (getData, addData, createSchema)
 Move over webhooks (w/o having to redo them!)
 Move over warns

**Comment by MDxWARRIORxOP** [comment]
But we cant merge mongo to main until we are self hosting the db, cause the latency is smtoo much

**Comment by MDxWARRIORxOP** [comment]
Also i dont think we can create helper functions like that, cuase shemas....

**Comment by MDxWARRIORxOP** [comment]
cool!

**Comment by NiceygyLive** [comment]
Next on the list: move data over from firestore

**Comment by NiceygyLive** [comment]
leveling done, just need to get the check cmd done ( and idealy delete old entries w/ `FindByIdAndReplace`) it wont update old entires, it will just add a new one. Not an issue just not effective. the bot will ignore all but the latest entry

**Comment by NiceygyLive** [comment]
next on the list is logging webhooks url, commit coming tonight

**Comment by NiceygyLive** [comment]
defo not in sch :P

**Comment by NiceygyLive** [comment]
We have first stable release! do i publish a release?

**Comment by NiceygyLive** [comment]
ToDo:

setIgnored
setWelcome
rank-Check
warnUser
channelCreate
channelDelete
guildCreate
guildMemeberAdd
GuildMemeberRemove

(most of these use the same function though)

**Comment by NiceygyLive** [comment]
setIngnored done (see 180c604 )
