### ISSUE TITLE
Collate all "create meme" cmds together 

### ISSUE THREAD

**Issue by NiceygyLive** [UFO-Studios/AlienBot-Discord#26]

**Comment by MDxWARRIORxOP** [comment]
so basically put all the cmds that make memes like /bobross, /ad, etc. in one cmd with subcommands

**Comment by MDxWARRIORxOP** [comment]
done, check commit: https://github.com/UFO-Studios/AlienBot-Discord/commit/793d27c3e85965471670f1f9a48d26f6441a9676
