### ISSUE TITLE
Banned words toggle not working

### ISSUE THREAD

**Issue by NiceygyLive** [UFO-Studios/AlienBot-Discord#29]
@TheAlienDoctor

**Comment by TheAlienDoctor** [comment]
> Firebase issue, will be fixed in next release 

Poggeroni, its like Pepperoni but pog.

**Comment by MDxWARRIORxOP** [comment]
@NiceygyLive

**Comment by MDxWARRIORxOP** [comment]
@NiceygyLive is it still not working?

**Comment by MDxWARRIORxOP** [comment]
its been over a month o.o

**Comment by MDxWARRIORxOP** [comment]
this is now fixed
