### ISSUE TITLE
Kick cmd broken

### ISSUE THREAD

**Issue by NiceygyLive** [UFO-Studios/AlienBot-Discord#32]
`DiscordAPIError[10062]: Unknown interaction
2|BETA     |     at SequentialHandler.runRequest (/home/ufo-vps/alienbot-discord-mongo/node_modules/@discordjs/rest/dist/index.js:659:15)
2|BETA     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2|BETA     |     at async SequentialHandler.queueRequest (/home/ufo-vps/alienbot-discord-mongo/node_modules/@discordjs/rest/dist/index.js:458:14)
2|BETA     |     at async REST.request (/home/ufo-vps/alienbot-discord-mongo/node_modules/@discordjs/rest/dist/index.js:902:22)
2|BETA     |     at async ChatInputCommandInteraction.reply (/home/ufo-vps/alienbot-discord-mongo/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:110:5)
2|BETA     |     at async Object.execute (/home/ufo-vps/alienbot-discord-mongo/events/interactionCreate.js:60:11) {
2|BETA     |   requestBody: { files: [], json: { type: 4, data: [Object] } },
2|BETA     |   rawError: { message: 'Unknown interaction', code: 10062 },
2|BETA     |   code: 10062,
2|BETA     |   status: 404,
2|BETA     |   method: 'POST',
2|BETA     |   url: 'https://discord.com/api/v10/interactions/1048569773212061696/aW50ZXJhY3Rpb246MTA0ODU2OTc3MzIxMjA2MTY5Njo5WTV3d1FhZXc1dWZ0RFppWDE1V1YzVDhWcEpxN3BSZUV5bHBoN2U3MDNWaUcwcjZ1a2xQVThrVTc3d2tKckNjTUJjU0Nlak1EQk5jYnlQNGtVbloyN205UktiaXgzeGc3SWl1MHAzWUlTVVpTMjJKczllcGFPdjNGQjBRWkU3Rw/callback'
2|BETA     | }`

**Comment by MDxWARRIORxOP** [comment]
uh nicey, its not broken
